filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/suricata/eve.json
    json.keys_under_root: true
    json.add_error_key: true

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  index: "suricata-%{+yyyy.MM.dd}"

setup.kibana:
  host: "kibana:5601"

setup.template.enabled: true
setup.template.name: "suricata"
setup.template.pattern: "suricata-*"

logging.level: warning
