apiVersion: 1

datasources:
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: suricata-*
    jsonData:
      timeField: '@timestamp'
    isDefault: true
